# Generated by Django 5.0.3 on 2024-03-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ipads',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='period',
        ),
        migrations.AddField(
            model_name='booking',
            name='periods',
            field=models.ManyToManyField(to='booking.period'),
        ),
    ]
