# Generated by Django 5.0.3 on 2024-03-17 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_remove_booking_ipads_remove_booking_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_ipads',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
